var com = {
	"qmino":{
		"miredot":{
		},
	},
};
com.qmino.miredot.restApiSource = {
	"projectName":"Mudrod :: Service",
	"projectVersion":"0.0.1-SNAPSHOT",
	"projectTitle":"Mudrod :: Service-0.0.1-SNAPSHOT",
	"buildSystem":"maven 3",
	"miredotVersion":"2.0.1",
	"miredotRevision":"55309abbe842+",
	"jsonDocEnabled":true,
	"jsonDocHidden":false,
	"singlePage":false,
	"hideLogoOnTop":false,
	"dateOfGeneration":"2016-10-03 13:38:58",
	"validLicense":true,
	"licenseErrorMessage":[
		
	],
	"onlineLicense":false,
	"loginUrl":null,
	"licenseType":"PRO",
	"allowUsageTracking":true,
	"licenseHash":"2484410021095167941",
	"baseUrl":"http://www.example.com",
	"applicationPath":"",
	"issuesTabHidden":false,
};

com.qmino.miredot.restApiSource.tos = {
	"javax_ws_rs_core_MediaType_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_MediaType_in",
		"content":[
		],
	},
	"javax_ws_rs_core_MediaType_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_MediaType_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Response_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Response_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response_out",
		"content":[
		],
	},
	"javax_ws_rs_core_UriBuilder_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriBuilder_in",
		"content":[
		],
	},
	"javax_ws_rs_core_UriBuilder_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_UriBuilder_out",
		"content":[
		],
	},
	"javax_ws_rs_core_NewCookie_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_NewCookie_in",
		"content":[
		],
	},
	"javax_ws_rs_core_NewCookie_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_NewCookie_out",
		"content":[
		],
	},
	"javax_ws_rs_core_EntityTag_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_EntityTag_in",
		"content":[
		],
	},
	"javax_ws_rs_core_EntityTag_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_EntityTag_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Response$StatusType_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response$StatusType_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Response$StatusType_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Response$StatusType_out",
		"content":[
		],
	},
	"javax_ws_rs_core_Link_in":{
		"type":"complex",
		"name":"javax_ws_rs_core_Link_in",
		"content":[
		],
	},
	"javax_ws_rs_core_Link_out":{
		"type":"complex",
		"name":"javax_ws_rs_core_Link_out",
		"content":[
		],
	},
};
com.qmino.miredot.restApiSource.enums = {
	"javax_ws_rs_core_Response$Status$Family":{
		"type":"enum",
		"name":"javax.ws.rs.core.Response$Status$Family",
		"values":[
			{
				"name":"INFORMATIONAL",
				"comment":null,
			},
			{
				"name":"SUCCESSFUL",
				"comment":null,
			},
			{
				"name":"REDIRECTION",
				"comment":null,
			},
			{
				"name":"CLIENT_ERROR",
				"comment":null,
			},
			{
				"name":"SERVER_ERROR",
				"comment":null,
			},
			{
				"name":"OTHER",
				"comment":null,
			},
		],
	},
};
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].content = [
	{
		"name":"type",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"parameters",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"wildcardType",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"subtype",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"wildcardSubtype",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].content = [
	{
		"name":"length",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"language",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.util.Locale",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"location",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"metadata",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"object",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"status",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"entity",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"object",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"links",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"],
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"lastModified",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"date",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"headers",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"object",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusInfo",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"allowedMethods",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"entityTag",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"stringHeaders",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"collection",
				"typeValue":{
					"type":"simple",
					"typeValue":"string",
				},
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"cookies",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"],
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"mediaType",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_MediaType_out"],
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].content = [
	{
		"name":"name",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"value",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"path",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"domain",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"version",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"comment",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"maxAge",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"expiry",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"date string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"secure",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"httpOnly",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_NewCookie_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].content = [
	{
		"name":"value",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"weak",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"boolean",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_EntityTag_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].content = [
	{
		"name":"family",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.enums["javax_ws_rs_core_Response$Status$Family"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"statusCode",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"number",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"reasonPhrase",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response$StatusType_out"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].content = [
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_in"].comment = null;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].content = [
	{
		"name":"type",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"title",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"params",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"map",
			"typeKey":{
				"type":"simple",
				"typeValue":"string",
			},
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"uri",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"java.net.URI",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"uriBuilder",
		"comment":null,
		"fullComment":null,
		"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_UriBuilder_out"],
		"deprecated":false,
		"required":false,
	},
	{
		"name":"rel",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"simple",
			"typeValue":"string",
		},
		"deprecated":false,
		"required":false,
	},
	{
		"name":"rels",
		"comment":null,
		"fullComment":null,
		"typeValue":{
			"type":"collection",
			"typeValue":{
				"type":"simple",
				"typeValue":"string",
			},
		},
		"deprecated":false,
		"required":false,
	},
];
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].ordered = false;
com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Link_out"].comment = null;
com.qmino.miredot.restApiSource.interfaces = [
	{
		"beschrijving":"",
		"url":"/autocomplete/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1971134413",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/vocabulary/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1045417918",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/recommendation/{shortname}",
		"http":"PUT",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1065248765",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"shortname",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/hrecommendation/{shortname}",
		"http":"PUT",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1431695457",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"shortname",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/vocabulary/{concept}",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1738167263",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"query",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/metadata/{query}-{operator}",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"708588683",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"query",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
				{
					"name":"term",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/recommendation/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"360263157",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/metadata/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-1135570244",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/autocomplete/{term}",
		"http":"POST",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"application/json",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"1064674312",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
				{
					"name":"term",
					"typeValue":{
						"type":"simple",
						"typeValue":"string",
					},
					"comment":null,
					"jaxrs":"PATH",
				},
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/datasetdetail/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"118566076",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/sessiondetail/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"2073030370",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
	{
		"beschrijving":"",
		"url":"/hrecommendation/status",
		"http":"GET",
		"title":null,
		"tags":[
			
		],
		"authors":[
			
		],
		"compressed":false,
		"deprecated":false,
		"consumes":[
		],
		"produces":[
			"text/html",
		],
		"roles":[
		],
		"rolesAllowed":null,
		"permitAll":false,
		"output":{
			"typeValue":com.qmino.miredot.restApiSource.tos["javax_ws_rs_core_Response_out"],
			"comment":null,
		},
		"statusCodes":[
		],
		"hash":"-582566567",
		"responseHeaders":{
			"headers":[
			],
			"customHeaders":[
			],
		},
		"inputs":{
			"PATH":[
			],
			"QUERY":[
			],
			"BODY":[
			],
			"HEADER":[
			],
			"COOKIE":[
			],
			"FORM":[
			],
			"MATRIX":[
			],
		},
	},
];
com.qmino.miredot.projectWarnings = [
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1971134413",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1971134413",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1971134413",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1971134413",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1045417918",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1045417918",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1045417918",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1045417918",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1065248765",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1065248765",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1065248765",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":"shortname",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1065248765",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1065248765",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1431695457",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1431695457",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1431695457",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":"shortname",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1431695457",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1431695457",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"hybridRecommendation",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"query",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_EXCEPTION_DOCUMENTATION",
		"description":"Exception thrown by method has no comment",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"java.io.IOException",
	},
	{
		"category":"JAVADOC_MISSING_EXCEPTION_DOCUMENTATION",
		"description":"Exception thrown by method has no comment",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"javax.servlet.ServletException",
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PATH_PARAM",
		"description":"A @PathParam is used in the method signature, but not found in the service URL",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"query",
	},
	{
		"category":"REST_UNMAPPED_EXCEPTION",
		"description":"Exception is thrown by interface specification, but is not mapped in the MireDot configuration. As such, the return errorcode can not be documented properly.",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"java.io.IOException",
	},
	{
		"category":"REST_UNMAPPED_EXCEPTION",
		"description":"Exception is thrown by interface specification, but is not mapped in the MireDot configuration. As such, the return errorcode can not be documented properly.",
		"failedBuild":"false",
		"interface":"1738167263",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchVocabResource",
		"implementationMethod":"searchVocabulary",
		"entity":"javax.servlet.ServletException",
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":"query",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":"term",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":null,
	},
	{
		"category":"JAXRS_MISSING_PATH_PARAM",
		"description":"A @PathParam is used in the method signature, but not found in the service URL",
		"failedBuild":"false",
		"interface":"708588683",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"searchMetadata",
		"entity":"term",
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"360263157",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"360263157",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"360263157",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"360263157",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.RecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-1135570244",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-1135570244",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-1135570244",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-1135570244",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchMetadataResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"1064674312",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"autoComplete",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"1064674312",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"autoComplete",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing parameter documentation",
		"failedBuild":"false",
		"interface":"1064674312",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"autoComplete",
		"entity":"term",
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"1064674312",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"autoComplete",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"1064674312",
		"implementationClass":"esiptestbed.mudrod.services.autocomplete.AutoCompleteResource",
		"implementationMethod":"autoComplete",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"118566076",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchDatasetDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"118566076",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchDatasetDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"118566076",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchDatasetDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"118566076",
		"implementationClass":"esiptestbed.mudrod.services.search.SearchDatasetDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"2073030370",
		"implementationClass":"esiptestbed.mudrod.services.search.SessionDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"2073030370",
		"implementationClass":"esiptestbed.mudrod.services.search.SessionDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"2073030370",
		"implementationClass":"esiptestbed.mudrod.services.search.SessionDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"2073030370",
		"implementationClass":"esiptestbed.mudrod.services.search.SessionDetailResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_SUMMARY",
		"description":"Missing summary tag",
		"failedBuild":"false",
		"interface":"-582566567",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_INTERFACEDOCUMENTATION",
		"description":"Missing interface documentation",
		"failedBuild":"false",
		"interface":"-582566567",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_PARAMETER_DOCUMENTATION",
		"description":"Missing return type documentation",
		"failedBuild":"false",
		"interface":"-582566567",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
	{
		"category":"JAVADOC_MISSING_AUTHORS",
		"description":"No author(s) specified for interface.",
		"failedBuild":"false",
		"interface":"-582566567",
		"implementationClass":"esiptestbed.mudrod.services.recommendation.HybridRecomDatasetsResource",
		"implementationMethod":"status",
		"entity":null,
	},
];
com.qmino.miredot.processErrors = [
];
var customHttpMethods = [
];

