# Site settings
title: MUDROD
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mudrod.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

github: https://github.com/mudrod
google_analytics:

paginate: 10
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

permalink : /:title/
